로또 게임 1단계 리뷰 요청 드립니다!
kiworkshop/java-lotto pull request #10
Opened 2021-07-07 16:35 UTC by seongbeenkim

안녕하세요 시영 선생님
1단계 로또 게임 리뷰 요청드립니다!

### 학습 로그
[equals() and hashCode()](https://velog.io/@sonypark/Java-equals-hascode-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C)
- equals를 재정의 해주지 않으면, 클래스의 인스턴스는 같은 속성 값을 가지더라도 비교 시, 다른 인스턴스로 간주하기 때문에 재정의 해줘야한다.
- hashcode를 재정의 해주지 않으면 같은 속성 값을 가지는 객체는 같은 해시값을 가질 수 없을 수 있다. 그렇기 때문에 hashcode를 재정의 해줘야한다. 

[enum](https://velog.io/@kyle/%EC%9E%90%EB%B0%94-Enum-%EA%B8%B0%EB%B3%B8-%EB%B0%8F-%ED%99%9C%EC%9A%A9)
- enum 특성 및 활용

[HashMap](https://www.notion.so/seongbeenkim/HashMap-806bd721c4294de391f55a95bdb59229)
- `HashTable`, `HashMap`, `ConcurrentHashMap`의 차이점

2021-07-15 00:37 UTC, KIMSIYOUNG requested changes
성빈 선생님 안녕하세요🙂

객체 분리를 잘 해주셔서 읽기 좋은 코드가 된 것 같아요. 

고민해보면 좋을 것들에 대해서 조금 작성했는데 확인 부탁드립니다.

2021-07-15 00:37 UTC, KIMSIYOUNG commented on README.md
> +- [x] 입력
꼼꼼한 기능 목록 작성👏

다음에는 가능하다면, 어떤 프로그램인지도 간략하게 적어주면 이해하는데 더 도움이 될 것 같아요!

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +    private NumberOfTickets numberOfTicketsFrom(final String inputPurchaseAmount) {
메소드 네이밍 컨벤션은 동사인데요. getter같은 경우는 취향따라 get을 제거하기도 하지만 일반적으론 동사를 사용하기 때문에, 변경해주시면 좋을 것 같습니다.

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/OutputView.java
> +        if (rank.getKey().equals(LottoRank.SECOND)) {
View가 도메인에 대한 로직을 자세히 알고 있네요. 도메인이 그렇다고, View를 위해서 가공해주는 것도 이상한데

이 경우 어떤 방법으로 둘간의 의존성을 약화시킬 수 있을까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        this(Integer.parseInt(inputPurchaseAmount));
타입에 대한 Validation을 추가해주시고 테스트도 추가해주시면 좋을 것 같아요. 

추가로 타입에 대한 Validation은 도메인에서 하는게 맞을지, 입력단에서 해야하는지 고민해보아요.

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        return new NumberOfTickets(purchaseAmount / LOTTO_TICKET_PRICE);
1200원을 입력하는 경우는 200원은 사라지는 금액이 되네요.

요구사항에 있는건 아니지만, 이 부분은 어떻게 가져갈 것인지 고민해보시고 TC도 같이 작성해주세요!

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningNumbers.java
> +        return Arrays.stream(winningNumbers.split(DEFUALT_DELIMITER))
입력값을 `trim` / `parse` 하는 것들이 도메인의 역할인지 입력단에서 처리해줘야하는 부분인지 고민해보면 좋을 것 같아요.

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningNumbers.java
> +        List<LottoNumber> lottoNumbers = lottoTicket.lottoNumbers();
현재구조는, 당첨번호에서 티켓을 꺼내와서 비교하는 형태인데요. 다른 객체의 값을 꺼내서 비교하는 형태보다, 다른 객체에게 메시지를 보내는건 어떨까요?

로또티켓에게, 같은 번호가 몇개인지 메시지를 보낼 수 있을 것 같아요.

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final List<LottoResult> lottoResults;
인스턴스 변수로 가지고 있어야하는 이유가 있을까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +        this.lottoResults = new ArrayList<>(lottoResults);
불변으로 객체를 생성해주셨네요. 👏

null값에 대한 대응도 같이해주면 좋을 것 같아요. null이 들어오는 경우 countRanks에서 널포인트가 나겠죠?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .filter(lottoRank -> lottoRank.matchedCount() >= FIFTH.matchedCount())
FIFTH.matchedCount보단, 해당 Enum에서 케이스에 대한 Enum들을 반환해주는 건 어떨까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .forEach(lottoRank -> ranks.put(lottoRank, ranks.getOrDefault(lottoRank, EMPTY) + 1));
메소드를 분리하거나 보다 의도를 드러낼 수 있는 방법이 없을까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +    public float profit(final NumberOfTickets numberOfTickets) {
혹시 double과 float을 함께 사용하시는 이유가 있을까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/test/java/lotto/domain/PurchaseAmountTest.java
> +        assertThatIllegalArgumentException()
요렇게도 표현할 수 있습니다! 저는 예외클래스가 눈에 보여서 요걸 더 선호하는데, 선호하시는걸 사용하시면 될 것 같습니다ㅎㅎ
```
        assertThatThrownBy(() -> new PurchaseAmount(999))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("최소 구입 금액은 1,000원 이상이여야 합니다.");
```

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/test/java/lotto/domain/WinningStatisticsTest.java
> +        //given //when
여기서 given은 없는 것 같아요. (beforeEach가 given으로 보이네용!)

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/NumberOfTickets.java
> +    public int value() {
value도 좋지만, Integer나 Long타입에서 지원하듯 intValue()는 어떨까요?

2021-07-15 00:37 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningNumbers.java
> +    public boolean equals(Object o) {
해당 클래스에 equals and hashcode를 재정의하신 이유가 있을까요?

2021-07-15 11:27 UTC, seongbeenkim commented on README.md
> +- [x] 입력
넵넵!! 간략하게 프로그램 설명 추가해주었습니다!

2021-07-15 13:11 UTC, seongbeenkim commented on src/main/java/lotto/controller/LottoController.java
> +    private NumberOfTickets numberOfTicketsFrom(final String inputPurchaseAmount) {
예전에 TDD 강의 수강할 때
`빌더(값을 반환하는 메서드)`는 `명사`로
`조정자(객체의 상태를 수정하는 메서드)`는 `동사`로 이름 지어보는 연습을 했었는데
이번 과정에서도 다시 한 번 공부해보자는 의미로 값을 반환하는 메서드에 명사도 적용을 한 부분이었습니다!

getter에서 get 빼준 부분 -> get 추가
명사인 메서드 -> 의미있는 동사 추가 하였습니다!!

2021-07-16 20:45 UTC, seongbeenkim commented on src/main/java/lotto/view/OutputView.java
> +        if (rank.getKey().equals(LottoRank.SECOND)) {
DTO 추가하여 `Domain`, `View` 사이의 의존성을 약화시키는 방향으로 수정하였습니다!
혹시 어떤 다른 방법이 있을 지 여쭤봐도 될까요?

2021-07-16 23:08 UTC, seongbeenkim commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        this(Integer.parseInt(inputPurchaseAmount));
해당 부분 `입력 -> DTO -> 도메인` 으로 나눠서
`입력`은 입력 형식만 지켜 문자열 또는 문자열 리스트 반환
`DTO`는 타입에 대한 검증
`도메인` 실제 데이터 유효성 검증
역할을 분배하여, `DTO`에 Validation 테스트 코드 추가해주었습니다!

2021-07-16 23:16 UTC, seongbeenkim commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        return new NumberOfTickets(purchaseAmount / LOTTO_TICKET_PRICE);
구입 금액 입력 시, 1000원 단위가 아닐 경우 예외가 발생하도록 수정하였습니다!

2021-07-16 23:18 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningNumbers.java
> +        return Arrays.stream(winningNumbers.split(DEFUALT_DELIMITER))
https://github.com/kiworkshop/java-lotto/pull/10#discussion_r671564323 에서 말씀드린것과 같이 입력은 입력 형식만 지켜 문자열 또는 문자열 리스트 반환하는 역할을 하도록 기준을 잡았기 때문에
`trim / parse` 부분은 입력단에서 처리해주는 게 더 적합하다고 생각하여 위의 로직 InputView로 옮겨주었습니다!

2021-07-16 23:22 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningNumbers.java
> +        List<LottoNumber> lottoNumbers = lottoTicket.lottoNumbers();
넵넵 이 부분 말씀하신 것처럼 메세지를 보내는 것이 더 좋은 것 같네요!
해당 부분 수정해주었습니다!

2021-07-17 16:23 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final List<LottoResult> lottoResults;
피드백을 받고 확인해보니 `lottoResults`가 인자로 받아 연산에 수행되는 변수이기 때문에 인스턴스 변수로 가질 필요가 없네요!
인스턴스 변수 제거하였습니다!

2021-07-17 16:55 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningStatistics.java
> +        this.lottoResults = new ArrayList<>(lottoResults);
넵넵!! 해당 부분 null일 경우 예외가 발생하도록 수정하였습니다!!

2021-07-17 17:01 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .filter(lottoRank -> lottoRank.matchedCount() >= FIFTH.matchedCount())
하나씩 값을 꺼내서 비교하는 것이 좋지 않다라고 피드백 주신 것으로 받아들였는데 맞을까요?

해당 Enum에 자신의 당첨 등수가 5등 미만인지 확인하는 메세지를 보내는 방식으로 수정하였습니다!

2021-07-17 17:05 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .forEach(lottoRank -> ranks.put(lottoRank, ranks.getOrDefault(lottoRank, EMPTY) + 1));
일단 먼저 해당 부분 메소드로 분리를 하였습니다!!
보다 의도를 드러낸다면, `lottoResults`를 일급컬렉션으로 만든 후, 메세지를 보내는 방법도 있을 것 같습니다!

2021-07-17 17:33 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningStatistics.java
> +    public float profit(final NumberOfTickets numberOfTickets) {
앗.. 따로 없습니다! 
`/` 연산 결과가 double인 것을 알지 못하고 구현을 했던 부분이었어서 float으로 통일해주었습니다!

2021-07-17 17:35 UTC, seongbeenkim commented on src/test/java/lotto/domain/PurchaseAmountTest.java
> +        assertThatIllegalArgumentException()
넵넵 알려주셔서 감사합니다!
두 가지 모두 참고해서 사용해보도록 하겠습니다 :)

2021-07-17 17:38 UTC, seongbeenkim commented on src/test/java/lotto/domain/WinningStatisticsTest.java
> +        //given //when
넵넵 해당 부분 뿐만아니라 다른 코드에서 불필요한 /given 제거해주었습니다!

2021-07-17 17:47 UTC, seongbeenkim commented on src/main/java/lotto/domain/NumberOfTickets.java
> +    public int value() {
넵넵 기본적으로 지원하는 이름을 사용하기 때문에 더 좋은 네이밍인 것 같습니다!
수정해주었습니다!!

2021-07-17 18:26 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningNumbers.java
> +    public boolean equals(Object o) {
실제 현실에서의 `로또 당첨 번호`를 생각을 했었습니다.
많은 사람들이 자신의 로또 번호를 당첨 번호와 비교할 때, 
이 당첨 번호가 모두에게 동일하게 인식되야 하지 않을까라고 생각하면서 `equal and hashcode`를 재정의해줬습니다.

하지만, 피드백을 받고 생각해보니
로또 번호를 비교하는 입장에서는 당첨 번호 객체가 같은지 신경 쓸 필요가 없고 번호들만 일치하는지 확인하면 되고, 
그리고 확률상으로는 정말 어렵겠지만, 지난 주 당첨 번호와 이번 주 당첨 번호가 같을 경우도 있기 때문에 이럴 경우에는 당첨 번호를 구별을 할 수 없다는 생각이 들었습니다.

이를 통해서 equals and hashcode 제거하였습니다!

2021-07-23 09:09 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +    private NumberOfTickets numberOfTicketsFrom(final String inputPurchaseAmount) {
앗 제가 몰랐던 부분이네요🙂 감사합니다. 

편하신대로 사용하시면 될 것 같아요. 

기본 컨벤션이 동사임을 모르고 계실까봐 드린 리뷰인데 배우고 갑니당!!

2021-07-23 09:11 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/OutputView.java
> +        if (rank.getKey().equals(LottoRank.SECOND)) {
네네! DTO를 의도한 코멘트였습니다🙂

2021-07-23 09:12 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        this(Integer.parseInt(inputPurchaseAmount));
네네! 좋은 것 같습니다.

유효성 검증은 어디서 해야하는가? 라는 주제에서 정답은 없지만 성빈선생님이 말씀하신 것과 비슷하게 저도 생각하고 있어요.
`각 계층/객체별로 검증해야하는 부분이 따로 있고 각 계층에서 그 검증을 담당해야 한다.`

2021-07-23 09:15 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .filter(lottoRank -> lottoRank.matchedCount() >= FIFTH.matchedCount())
네네, 맞습니다.

등수를 관리하는 Enum에서 로또를 맞춘 갯수를 기반으로 당첨 대상인지 아닌지 판단하는게 맞다라고 생각했어요.
통계라는 이름이 포괄적이기 때문에, 각 객체들의 값을 가져와서 써도 될 것 같은 느낌이지만 `누가 해야하는 역할이며 누구에게 메시지를 보내는게 자연스러운가` 라고 봤을 때는 Enum쪽 이라고 판단했습니다🙂

2021-07-23 09:17 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .forEach(lottoRank -> ranks.put(lottoRank, ranks.getOrDefault(lottoRank, EMPTY) + 1));
네네.좋습니다!

통계라는 클래스 안에서 이를 다루고 있지만 각 등수에 몇개가 당첨이 되었는가를 계산하는 로직이기에 그 의미를 조금 더 드러내는게 좋다고 생각했습니다. 잘 반영해주셨어요🙂

2021-07-23 09:26 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/WinningNumbers.java
> +    public boolean equals(Object o) {
네네! 좋은 생각인 것 같습니다.

의도와 다르게 이해될 수 있는 코드들은 지금처럼 제거해주시면 좋을 것 같습니다.
처음 보고 모든 값이 같다면 같은 객체로 사용할 순 있겠다. 다만 그렇게 되면 일부가 다른 경우를 판단할 때는 다른 메소드로 판단해야 하는데 이걸 값객체로 사용해야하는 이유가 있는가? 라는 의문이 들었었어요🙂

추가적으로 저는 `1등만을 판단하는 로또 게임`이라고 요구사항이 변경되는 경우에도 해당 클래스에 equals & hashCode를 정의하지 않고 isAllMatch와 같은 메소드로 판단할 것 같아요.
저도 경험한 바운더리가 적지만, 값 객체는 금액이나, 날짜 등 primitive타입을 포장해 유의미한 메소드를 만들고 타입안정성을 지키기 위한 용도로 주로 사용했고, 보아왔기 때문에 해당 방식으로 구현되는 건 처음 볼 때 이해의 어려움이 있지 않을까? 라고 생각해요! 

추가 의견은 개인적인 생각일 뿐이니, 편하신대로 하시면 될 것 같습니다🙂

2021-07-23 09:28 UTC, KIMSIYOUNG approved these changes
성빈 선생님 안녕하세요.

리뷰 반영 잘 해주셨네요. 1단계는 여기서 머지하도록 하겠습니다🙂

코멘트 주신 부분은 댓글 달아두었으니 확인해주시고, 궁금하신 내용 있으시면 편하게 DM 주세요. 고생하셨습니다!!

2021-07-23 09:29 UTC, merged

2021-07-23 09:49 UTC, seongbeenkim commented on src/main/java/lotto/controller/LottoController.java
> +    private NumberOfTickets numberOfTicketsFrom(final String inputPurchaseAmount) {
시영 선생님이 메서드 네이밍에 대한 리뷰를 주셔서, 다른 사람이 코드를 읽었을 때 잘 이해할 수 있는 이름을 어떻게 지을 수 있을까에 대해서 더 고민해볼 수 있었습니다 감사합니다! :)

2021-07-23 11:27 UTC, seongbeenkim commented on src/main/java/lotto/domain/PurchaseAmount.java
> +        this(Integer.parseInt(inputPurchaseAmount));
각 계층/객체별로 가져야 할 역할과 책임에 대해서 고민해본 시간이었던 것 같습니다!! 감사합니다 :)

2021-07-23 11:42 UTC, seongbeenkim commented on src/main/java/lotto/domain/WinningNumbers.java
> +    public boolean equals(Object o) {
넵넵 시영 선생님 의견에 동의합니다!!
2단계에서는 각 객체의 역할과 용도를 더 고민하고 구현해보도록 하겠습니다!
감사합니다 :)