Ariel429
kiworkshop/java-lotto pull request #12
Opened 2021-07-11 18:20 UTC by Ariel429

## 학습로그
### 1. Util성 클래스 생성 및 사용 (Class InputValidation)
- Java util, Apache Commons 등의 오픈소스가 아닌, 개발자가 직접 만들어서 사용할 수도 있음. 
- 싱글턴 또는 정적 유틸클래스 사용 지양  -> 필요자원을 생성자에 넘겨주어 의존객체를 주입
- 클래스가 내부적으로 여러 자원에 의존하는 경우
- 클래스 동작에 영향을 주는 경우

### 2. 일급클래스
```
private static List<Integer> toIntegers(List<String> input) {
        return new ArrayList<>(Collections.unmodifiableList(input.stream()
                .mapToInt(Integer::parseInt)
                .boxed()
                .collect(Collectors.toList())));
    }
```

- 당첨번호를 return하는 과정에서 unmodifiableList 사용
- 당첨된 번호를 불변의 상태로 유지하며 반환하더라도 변경불가
- 좀 더 다양한 곳에 차용할 필요가 있음

### 3. 스트림에서의 중복 요소 제거 .stream().distinct().count()

```
private void checkDuplicate(List<Integer> winningNumbers) {
        int countOfDeDuplication = (int) winningNumbers.stream()
                .distinct()
                .count();

        if (countOfDeDuplication != winningNumbers.size()) {
            throw new IllegalArgumentException(ALERT_CHECK_DUPLICATION);
        }
    }
```

- 원본 리스트의 size()와 stream에서 distinct().count() 정보를 비교하여 중복된 요소가 있는지를 확인할 수 있음

### 4. Enum의 활용 (RANK)
Enumeration, 열거_ 서로 관련된 상수들의 집합
- 특정 클래스가 상수만으로 이뤄진 경우 class로 선언하기보다 enum으로 선언하여, 상수의 집합임을 나타낼 수 있다.
- Enum에서 선언한 상수는 클래스 로드 시, 하나의 인스턴스로 생성되어 싱글톤 형태로 어플리케이션 전체에서 사용 가능하다.
- java.lang.enum 클래스를 상속하고, 자바는 다중 상속을 지원하지 않으므로 Enum은 다른 클래스를 상속받을 수 없다.
- 참고 링크: 
https://velog.io/@kyle/%EC%9E%90%EB%B0%94-Enum-%EA%B8%B0%EB%B3%B8-%EB%B0%8F-%ED%99%9C%EC%9A%A9

2021-07-13 12:44 UTC, wbluke requested changes
정애 선생님~ 꼼꼼한 테스트와 함께 구현하신 로직 잘 보았습니다. 좋네요 👍 
이제 어느정도 객체지향 설계의 맛을 보고 계신 것 같은데요 ㅎㅎ
더 견고한 소프트웨어를 위한 몇가지 피드백을 남겼으니 확인하시고 재요청 부탁드려요 🙂 
질문이 있으시면 언제든 코멘트나 DM 주시면 됩니다 !

2021-07-13 12:44 UTC, wbluke commented on src/main/java/controller/LottoController.java
> +    static OutputView outputView = new OutputView();
Controller에서 main을 가지고 있고, main이 static이기 때문에 InputView와 OutputView도 static이 되었는데요.
프로그램의 진입점인 main은 별도로 두고, main에서 Controller 인스턴스를 하나 생성해서 게임을 진행하는 형태는 어떨까요?

OOP에서 static은 기본적으로 안티패턴이기 때문에 꼭 필요한 곳에만 적시적소에 사용하고, 피할 수 있다면 피하는 것이 좋습니다.
지난 시간 자동차 라이브코딩에서 보여드렸던 구조를 참고해 보세요 :)
(InputView, OutputView를 정적 클래스로 만들라는 이야기는 아닙니다)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +public class InputValidation {
사용자 입력에 대한 책임을 별도로 분리하셨군요 👍  좋은 시도입니다 ㅎㅎ
다만 생각해볼 지점들이 있어서, 아래에 코멘트 남기겠습니다 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +    }
사용자 입력에 대한 validation을 진행할 때, 구분을 해볼 필요성이 있는데요.

1. 입력한 문자열이 숫자인가?
2. 입력한 숫자가 1과 45 사이의 숫자인가?

두 validation의 차이가 무엇일까요?

1번 validation은 사용자 입력이 의도한 포맷에 맞는 입력인지를 체크하는 로직이고,
2번 validation은 비즈니스 로직입니다.
즉, 2번 유효성 검사는 우리가 만들고 있는 로또 게임의 요구사항, 비즈니스 로직으로, View나 지금같은 Util성 클래스가 아니라
도메인의 로직으로 분류되고 관리되어야만 합니다.

어떻게 도메인 로직으로 가져올 수 있을까요? :)
(hint. 로또 숫자 하나를 Wrapping해 보세요)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +    }
> ## 2. 일급클래스
> 
> ```java
> private static List<Integer> toIntegers(List<String> input) {
>         return new ArrayList<>(Collections.unmodifiableList(input.stream()
>                 .mapToInt(Integer::parseInt)
>                 .boxed()
>                 .collect(Collectors.toList())));
>     }
> ```
> 
> - 당첨번호를 return하는 과정에서 unmodifiableList 사용
> - 당첨된 번호를 불변의 상태로 유지하며 반환하더라도 변경불가
> - 좀 더 다양한 곳에 차용할 필요가 있음

일급클래스에 대한 내용이 아닌 것 같은데요, 혹시 일급컬렉션과 헷갈리셨다면 일급컬렉션 또한 아닙니다 ㅎㅎ
한번 다시 확인해 주세요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +    private void validate(List<Integer> winningNumbers) {
이런 체크 로직도 결국은 입력 시점에 전부 검사하는 것이 아니라, 비즈니스 로직을 수행하면서 자연스럽게 validation이 되어야 합니다.
아래 checkBound() 메서드에도 피드백 남겼지만, 
로또 숫자 하나를 감싸서 의미를 부여하고, 다시 로또 숫자 리스트를 감싸서 `일급컬렉션`을 만들고 유효성 검사를 진행해봅시다.

`일급컬렉션`이 무엇인지 한번 학습해보고 적용해보아요 ㅎㅎ
https://jojoldu.tistory.com/412

2021-07-13 12:44 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +    }
추가적으로 이 클래스의 다른 곳에 있는 유효성 검사 로직들도 어떤 적절한 도메인 객체로 이동할 수 있을까 고민해 보세요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/LottoMachine.java
> +        }};
1. 왜 TreeMap을 사용하셨을까요? 보통 Map은 HashMap, EnumMap을 사용합니다.
2. 초기화 로직은 별도의 공간에 1회만 진행되도록 수정해보면 좋겠어요. 이 메서드를 호출할 때마다 매번 초기화를 진행하겠네요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/Lottos.java
> +public class Lottos {
사용하지 않는 클래스네요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/view/OutputView.java
> +        if (rank != Rank.ETC)
1. 자바 컨벤션에 따르면 if문에는 중괄호를 꼭 사용해 주세요.
2. rank.isEtc() 와 같이 Rank에게 메시지를 보내서 해결해보면 어떨까요? :)

2021-07-13 12:44 UTC, wbluke commented on src/test/java/domain/LottoMachineTest.java
> +        lottoMachine.getRankResult(lottoTicket, Arrays.asList(1, 2, 3, 4, 5, 6), 7);
메서드 이름은 getRankResult()인데, getter의 역할 보다 오히려 데이터 조작을 진행하고 있어서
아랫줄에 있는 getRankResult()를 검증하기 위해 반드시 먼저 수행되어야 하네요.
(지금 보니 이름도 동일하네요 ㅎㅎ)

메서드의 책임을 작은 단위로 쪼개고 구조를 명확하게 개선해볼 수 있을까요? :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/LottoMachine.java
> +                .mapToDouble((rank) -> rank.getKey().prize() * rank.getValue())
Rank에 메시지를 보내서 해결할 수 있을까요? :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/LottoMachine.java
> +        List<Integer> balls = IntStream.range(1, 45)
매번 로또 숫자를 뽑기 위한 후보 숫자들이 45개 생성될텐데요, 항상 동일한 풀이 생성되어야 하니 별도의 풀을 만들어서 캐싱해보면 어떨까요?
초기화할 때 로또 숫자 45개를 미리 생성해놓고 6개를 랜덤으로 뽑을 때 항상 같은 로또 숫자 인스턴스를 사용하는거죠 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/enums/Rank.java
> +    }
getPrize(), getMatched() 가 더 맞는 네이밍이겠네요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/Lotto.java
> +    private Rank rank;
### 객체지향 생활체조 원칙
6. 모든 엔티티를 작게 유지한다.
7. 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

---
Lotto가 matchCount와 bonusCount와 rank를 알아야만 할까요? 한번 고민해 보셔요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/Lotto.java
> +    public Lotto(List<Integer> randomNumber) {
random 숫자라는 의미를 Lotto는 몰라도 될 것 같아요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/Lotto.java
> +    }
위에도 코멘트 남겼지만, 
필드에 값을 가지고 있는 것이 좋은 것일지, 또 값을 반환하는 형태로 구성하면 어떤 장점이 있을지 한번 고민해 보세요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/Lotto.java
> +    public String getLottoNumberString() {
View에 관련된 로직이 아닐까 합니다 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/domain/LottoGenerator.java
> +public class LottoGenerator {
엇 이 친구는 프로덕션 코드에서 사용되지 않고 테스트만 하고 있는 객체이네요 :)

2021-07-13 12:44 UTC, wbluke commented on src/main/java/enums/Rank.java
> +public enum Rank {
Enum 사용 잘하셨어요!! 💯

2021-07-13 12:44 UTC, wbluke commented on README.md
> +### 기능 구현 리스트
![image](https://user-images.githubusercontent.com/44018338/125453123-5d064a3c-ab53-4096-9692-e01555c2e4aa.png)

2등 당첨을 발생시켜보았는데 위와 같은 버그가 있어요! :)

2021-07-13 12:44 UTC, wbluke commented on build.gradle
> +    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.0'
외부 라이브러리 사용 시도 좋네요 👍

2021-09-05 09:52 UTC, Ariel429 commented on src/main/java/utils/InputValidation.java
> +    private void validate(List<Integer> winningNumbers) {
InputValidation 클래스는 없어지고, PreConditionalUtil클래스가 남아서 
String -> Integer로 바꾸거나 null 또는 공백 입력의 경우를 확인해주고 있습니다. 

이런 로직도 분리해서 도메인 안으로 넣는 것이 좋을지, 더 좋은 방향으로 생각되시는 게 있다면 알려주세요!

2021-09-05 09:53 UTC, Ariel429 commented on src/main/java/utils/InputValidation.java
> +    private void validate(List<Integer> winningNumbers) {
InputValidation 클래스는 없어지고, PreConditionalUtil클래스가 남아서
String -> Integer로 바꾸거나 null 또는 공백 입력의 경우를 확인해주고 있습니다.

이런 로직도 분리해서 도메인 안으로 넣는 것이 좋을지, 더 좋은 방향으로 생각되시는 게 있다면 알려주세요!

2021-09-07 10:20 UTC, wbluke commented on src/main/java/LottoApplication.java
> +public class LottoApplication {
`Move this file to a named package` 라는 경고가 뜰텐데요.
모든 소스는 `/src/main/java` 하위에 특정 루트 패키지를 만들어서 관리해야 합니다.
lotto 와 같은 이름으로 메인 패키지를 지정하고 나머지 소스들(controller, domain 등)을 전부 옮기면 좋겠네요 :)

2021-09-07 10:20 UTC, wbluke commented on src/main/java/domain/WinningLotto.java
> +        checkBonusDuplicate(winningNumbers, bonusNumber);
WinningLotto의 생성자와 validation에 대해서 다시 생각해보면 좋겠는데요.

WinningLotto를 만들기 위해 LottoTicket 하나와 bonusBall인 LottoNumber 하나를 받으면
1등번호가 6개인지, 중복이 되는 번호인지, 보너스볼이 1~45 사이의 숫자인지 등의 validation은 자연스럽게 외부에서 완료되어 주입된 상태 아닐까요?ㅎㅎ 
(현재는 6개 체크, 중복 체크가 다른 객체에서 작성한 로직임에도 불필요하게 또 이루어지고 있고, 보너스볼에 대한 범위 보장은 받지 못하는 상태네요)

WinningLotto에서는 이미 검증이 끝난 객체들을 받았기 때문에 위에 말한 유효성은 보장을 받은 상태고, WinningLotto에서 체크해야 할 유효성은 checkBonusDuplicate 밖에 없을 것 같아요.
`naive한 숫자, 문자열 등의 값을 왜 VO로 포장하는가?` 에 대한 답을 얻어가시면 좋겠네요 :)

2021-09-07 10:20 UTC, wbluke commented on src/main/java/domain/WinningLotto.java
> +        if (isDuplicate) {
if문 내의 판단로직이 긴 이런 경우면 변수 추출보다는 메서드 분리가 낫습니다 :)

2021-09-07 10:20 UTC, wbluke commented on src/main/java/domain/WinningLotto.java
> +        return LOTTO_NUMBERS_SIZE - purchasedTicket.size();
getter로 꺼내서 작업을 하지 말고 purchasedLottoTicket에 winningNumbers를 넘기면서 메세지를 던지면 어떨까요?
좋은 OOP 설계 역량을 훈련하기 위한 좋은 방법 중 하나는 getter를 끝까지 사용하지 않고 로직을 풀어나가는 연습을 하는 것입니다.
처음부터 모든 객체를 만듦과 동시에 getter를 만들지 말고 꼭 필요한 순간에 getter를 만들어서 사용할 수 있도록 해보아요 :)

2021-09-07 10:20 UTC, wbluke commented on src/main/java/domain/WinningLotto.java
> +        return LOTTO_NUMBERS_SIZE - purchasedTicket.size();
그러면 매칭 카운트를 하기 위해서 `removeAll() & size의 차` 를 이용하기 보다 바로 stream 등으로 filter & count를 할 수 있을 것 같아요 :)

2021-09-07 10:20 UTC, wbluke commented on src/main/java/utils/InputValidation.java
> +    private void validate(List<Integer> winningNumbers) {
네네 정말 유틸성이라 생각되는 부분들만 유틸로 빼는 방법도 좋습니다.
다만 String에 관련된 것인지, Integer에 관련된 것인지 주제별로 분리를 해도 좋겠네요. (애플리케이션이 커짐에 따라 해당 클래스도 비대해질 것 같아요)

2021-09-07 10:24 UTC, wbluke approved these changes
잘 구현해 주셨네요 👍 
추가적인 피드백 남겼는데요, 다음 단계 진행하면서 같이 확인 부탁드려요 🙂

2021-09-07 10:24 UTC, wbluke commented on src/main/java/enums/Rank.java
> +        return false;
더 간단하게 작성해볼 수 없을까요? :)

2021-09-07 10:24 UTC, merged