로또게임 리뷰 요청드립니다.
kiworkshop/java-lotto pull request #13
Opened 2021-07-12 01:42 UTC by eunii

## 일급 객체
(참고) 일급객체
- 변수나 데이타에 할당 할 수 있어야 한다.
- 객체의 인자로 넘길 수 있어야 한다.
- 객체의 리턴값으로 리턴 할수 있어야 한다.

## 일급 컬렉션
collection 을 랩핑한 컬렉션
[참고사이트](https://jojoldu.tistory.com/412)

## enum
변수를 상수로 관리하는 자료형
[참고사이트](https://webdevtechblog.com/enum%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%83%81%EC%88%98%EA%B0%92-%EA%B4%80%EB%A6%AC-a3e3fb73eae1)

## codeWithme
인텔리제에에서 화면공유, 원격 지원을 할 수 있는 프로그램

## 객체지향 생활체조 원칙
[객체지향 생활체조 원칙] (https://7942yongdae.tistory.com/8)

2021-07-12 14:03 UTC, Deocksoo requested changes
안녕하세요 다은선생님,
작성해주신 코드 잘 읽어보았어요. 무척 정갈하고 읽기 좋은 코드네요 👍 
테스트도 꼼꼼하게 잘 작성해주셨구요.
덕분에 고민하고 계시는 부분들이 잘 보였던 것 같아요.
조금 더 생각해보시면 좋을 만한 부분들 코멘트 남겨보았으니, 확인 한 번 부탁드려요 :)

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/Lotto.java
> +    public void setRank(List<Integer> winningNumber, int bonusNumber) {
지금은 Lotto를 생성하고, setRank를 통해 몇 등에 당첨되었는지 설정해주고 있군요.
새로운 Lotto 객체를 만들었을 때, 그 객체는 setRank가 호출된 적이 있는지, 그런 적이 없는지에 따라서 두 가지 상태를 갖는 로또가 되겠네요. 그렇다면 getRank 메서드는 setRank가 호출된 적이 있는지 없는지에 따라 사용 가능한 상태인지, 아직 사용하면 안 되는지에 대한 여부가 결정되어 버릴텐데요, 그러면 문제가 될 만한 여지가 생기지 않을까요? 
시스템이 복잡해지고, 점점 많은 사람들이 이 프로젝트를 함께 개발하게 되면서 생길 수 있는 문제들을 한 번 생각해보시면 좋을 것 같아요.

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/Lotto.java
> +    private Rank rank;
matchCount, bonusCount, rank 세 가지 값을 Lotto 객체의 상태값으로서 선언해 주셨군요.
이렇게 필드로 선언하신 이유는 무엇인가요?
위 세 가지 상태값들은 Lotto 객체 안에 반드시 필요한 상태들인가요?

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/Lotto.java
> +    public String getLottoNumberString() {
이 부분은 Lotto 번호를 콘솔에서 잘 표현해주기 위해 사용하는 메서드군요.
View를 따로 분리해주셨는데, 그쪽에서 이 기능을 담당하도록 하는 것은 어떤가요?

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/LottoGenerator.java
> +    private static List<Integer> createBalls() {
static으로 선언한 이유가 있나요?

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/LottoMachine.java
> +    public List<Integer> createRandomNumber() {
같은 기능이 LottoGenerator에도 있는 것을 보니, 아마도 리펙토링 중이신 것이겠죠? :)

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/LottoMachine.java
> +    public List<Lotto> getRankResult(List<Lotto> lottos, List<Integer> winningNumber, int bonusNumber) {
이 메서드가 중간에 하나 들어가면서 많은 부분들이 애매해지고 있는 것 같아요.
Rank를 Lotto에서 분리해내고, 아래 메서드와 한 번 합쳐보는 것은 어떤가요?

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/domain/Lottos.java
> +public class Lottos {
아마 이 부분도 리펙토링 중이실 것 같네요.

2021-07-12 14:03 UTC, Deocksoo commented on src/main/java/utils/InputValidation.java
> +public class InputValidation {
Validation을 전문적으로 담당하는 클래스를 만들어주셨군요.
지금은 괜찮지만, 프로그램이 커지면 커질수록 이 클래스도 비대해지지 않을까요?
클래스가 비대해진 이유는 무엇인가요? 이 클래스가 다른 누군가가 책임져야 할 일들을 모두 떠맡고 있지는 않은가요? 
만약 이곳이 아니라면 어디에서 유효성을 검증할 수 있을까요?
객체지향의 관점에서 한 번 더 고민해보셔도 좋을 것 같아요.

2021-07-12 14:03 UTC, Deocksoo commented on src/test/java/domain/LottoGeneratorTest.java
> +        assertThat(lotto.getLottoNumbers().size()).isEqualTo(LOTTO_SIZE);
production code에 이미 선언해둔 상수로 검증하면 어떤가요?

2021-07-12 14:03 UTC, Deocksoo commented on src/test/java/domain/LottoGeneratorTest.java
> +    @DisplayName("1부터 45이하의 중복되지 않는 로또 번호 중 7개를 리턴한다")
테스트 내용과 다른것 같네요..!

2021-07-12 14:03 UTC, Deocksoo commented on src/test/java/utils/InputValidationTest.java
> +    @DisplayName("입력 숫자의 범위가 1-45가 아닐 경우 예외가 발생한다.")
Lower bound도 테스트하면 보다 꼼꼼하게 검증할 수 있을것 같네요.

2021-07-15 04:53 UTC, eunii commented on src/main/java/domain/Lotto.java
> +    public void setRank(List<Integer> winningNumber, int bonusNumber) {
setRank를 없애고 getRank()에 Rank를 계산해서 리턴하는것으로 수정하였습니다.

2021-07-15 04:55 UTC, eunii commented on src/main/java/domain/Lotto.java
> +    private Rank rank;
mattchCount와 bonusCount는 Rank를 계산하기 위한 값으로 Lotto에서는 필요 없는 값으로 삭제하였습니다. Rank도 getRank() 함수를 만들어서 호출시 Rank를 계산해서 리턴해주는 구조로 변경하였습니다

2021-07-15 04:55 UTC, eunii commented on src/main/java/domain/Lotto.java
> +    public String getLottoNumberString() {
해당 메서드 OutPutView로 이동하였습니다.

2021-07-15 04:56 UTC, eunii commented on src/main/java/domain/LottoGenerator.java
> +    private static List<Integer> createBalls() {
해당 클래스는 정리되지 않는 클래스로로 삭제 하였습니다.

2021-07-15 04:56 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +    public List<Integer> createRandomNumber() {
네ㅠㅠ 정리를미처 못했네요. 다시 정리하였습니다!

2021-07-15 05:00 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +    public List<Lotto> getRankResult(List<Lotto> lottos, List<Integer> winningNumber, int bonusNumber) {
어떤 의미로 하신 내용인지 조금 더 정확히 설명해주시면, 2차과제때 추가로 반영하겠습니다ㅠ RankResult객체를 따로 만들어서 분리해내라는 의미이신가요?

2021-07-15 05:00 UTC, eunii commented on src/main/java/domain/Lottos.java
> +public class Lottos {
정리하였습니다!

2021-07-15 05:02 UTC, eunii commented on src/main/java/utils/InputValidation.java
> +public class InputValidation {
Lotto번호는 Lotto객체에 validation체크, 당첨번호 및 보너스 번호는 LottoMachine, 기타 널 체크는 InputValication에 로 수정하였습니다. LottoMachine의 기능이 거대해지는것 같아서 LottoValication 클래스로 따로 뽑아낼지 고민중입니다.

2021-07-15 05:05 UTC, eunii commented on src/test/java/domain/LottoGeneratorTest.java
> +        assertThat(lotto.getLottoNumbers().size()).isEqualTo(LOTTO_SIZE);
해당 테스트는 리펙터링 과정에서 삭제하였으며, 앞으로 테스트 케이스를 작성할때 같은 값이면 production 코드에서 선언 한 상수를 쓰도록 하겠습니다.

2021-07-15 05:06 UTC, eunii commented on src/test/java/domain/LottoGeneratorTest.java
> +    @DisplayName("1부터 45이하의 중복되지 않는 로또 번호 중 7개를 리턴한다")
해당내용도 리펙터링 과정에서 삭제되었고, 테스트 목적과 구현을 확인해서 네이밍 하겠습니다.

2021-07-15 05:08 UTC, eunii commented on src/test/java/utils/InputValidationTest.java
> +    @DisplayName("입력 숫자의 범위가 1-45가 아닐 경우 예외가 발생한다.")
음수인 경우도 추가로 테스트케이스에 추가하였습니다

2021-07-16 17:09 UTC, Deocksoo approved these changes
안녕하세요 다은선생님 :) 반영해주신 부분들 확인하였어요. 
깔끔하게 정리하는 것이 쉽지 않으셨을텐데, 리뷰 반영하시느라 고생 많으셨어요.
Lotto 객체의 역할이 보다 명확해지고, 불변성도 보장할 수 있게 되었네요 👍 
훨씬 깔끔한 객체가 된 것 같아요. 
Lotto 객체가 정리되고 책임이 명확해지기 시작하면서 로또 게임을 구성하는 다른 부분들에 대해서도 보다 객체지향적인 방향으로 코드를 정리해볼 수 있는 여지가 생기기 시작한 것 같아요. 생각해보시면 좋을 만한 부분들 추가로 코멘트 남겨두었으니 확인 한 번 부탁드려요. 아직 원시타입이나 Java Collection을 또다른 객체로 포장하는 부분에 있어서 익숙하지 않으실 것 같은데, 왜 그럴 필요가 있는지 한 번 더 고민해보실 수 있는 질문들이었으면 좋겠네요.

아마 2단계도 계속 진행하시게 될 것 같아서, 남겨 드린 코멘트와 관련된 고민은 머지 후에 계속 진행해보시면 어떨까 싶어요. 남은 단계도 화이팅이에요.

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/domain/LottoMachine.java
> +    private static final String ALERT_CHECK_BONUS_DUPLICATE = "보너스볼이 당첨 번호와 중복되는지 확인해주세요.";
상수와 필드 변수는 구분해주시면 좋을 것 같아요

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/domain/LottoMachine.java
> +        TreeMap<Rank, Integer> result = new TreeMap<Rank, Integer>() {{
SonarLint 플러그인을 사용해보는 것은 어떤가요?
위와 같이 Double Brace Initialization을 통해 익명 클래스를 하나 생성하는 방식은 여러 가지 문제를 야기할 수 있겠어요.

> _Because Double Brace Initialization (DBI) creates an anonymous class with a reference to the instance of the owning object, its use can lead to memory leaks if the anonymous inner class is returned and held by other objects. Even when there's no leak, DBI is so obscure that it's bound to confuse most maintainers.
For collections, use Arrays.asList instead, or explicitly add each item directly to the collection._

>**Noncompliant Code Example**
 Map source = new HashMap() {{ // Noncompliant   
     put("firstName", "John");      
     put("lastName", "Smith");  
}};  

>**Compliant Solution**
  Map source = new HashMap(); 
// ...  
source.put("firstName", "John");  
source.put("lastName", "Smith");  
// ...  

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/controller/LottoController.java
> +        List<Lotto> lottoTickets = lottoMachine.getLottoTickets();
일급컬렉션에 대해서 학습해보셨던 것 같은데, 한 번 적용해보면 어떨까요?

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/domain/LottoMachine.java
> +     public List<Integer> getWinningNumber(String winningNumber) {
지금은 LottoMachine에서 이러한 유효성 검증을 수행하고, 그 결과로 Integer 값들을 리턴해주고 있군요.
시스템이 크지 않을 때에는 리턴받은 숫자들이 잘 검증되었다는 것을 충분히 확신할 수 있겠어요. 
잠깐 이 메서드에 들어와 보면 결과로 받은 List 안에 있는 숫자들이 특정 조건을 만족하도록 잘 만들어졌다는 것을 알 수 있으니까요.

그런데 시스템이 점점 발전하고, 거대해져서, 이 숫자들이 단순히 LottoController에서만 사용되는 것이 아니라,
또다른 Controller, 또다른 Service에서 사용되는 상황을 한 번 상상해보시면 어떨까요?
그러면 이 숫자들을 넘겨받은 곳에서 숫자가 검증된 숫자인 지 확신할 수 있을까요? 아마도 지금 리턴으로 되돌려주고 있는 Type만 보았을 때에는 100이든 1000이든 또다른 어떤 숫자든 넘어올 수 있기 때문에, 지금 Type만 보아서는 예상하기 어려운 상황이 될 것 같아요. 그럴 때마다 해당 숫자가 생성된 곳이 어디인지 다시 찾아들어가 확인해보고, 검증 조건 하나라도 바뀌는 날에는 어디에서 어떻게 사용되고 있는지, 조건이 바뀌어도 시스템에 이상이 없을지 다 찾아다니며 체크해야 할 텐데, 그러면 얼마나 시간이 오래 걸릴까요?

결국 시스템이 복잡해지면 복잡해 질수록 누가 언제 이 숫자들을 보더라도 "이 숫자들은 검증된 숫자" 라는 것을 확신할 수 있어야 해요. 그럴 수 있게 하려면 어떻게 해야 할 지 한 번 고민해보셔도 좋을 것 같아요 :)

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/utils/InputValidation.java
> +public class InputValidation {
Lotto 객체에서는 특별히 유효성 검증하는 부분이 보이지 않는데, 어느 객체를 말씀하신 것이었을까요?

2021-07-16 17:09 UTC, Deocksoo commented on src/main/java/domain/Lotto.java
> +        countOfBonusMatch(bonusNumber);
위 두 메서드는 호출하지 않아도 괜찮겠네요

2021-07-16 17:12 UTC, merged

2021-07-21 13:28 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +    private static final String ALERT_CHECK_BONUS_DUPLICATE = "보너스볼이 당첨 번호와 중복되는지 확인해주세요.";
넵ㅠ코드 정리하는 습관도 들여보겠습니다ㅠㅎㅎ

2021-07-21 13:29 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +        TreeMap<Rank, Integer> result = new TreeMap<Rank, Integer>() {{
SonarLint 추천 감사합니다 ㅎㅎ 설치 후 도움을 많이 받고 있어요. 이 건은 SonarLint에서 추천한 방법 말고 RankMap 으로 랩핑한번 더해서 거기서 초기화 해주었습니다.

2021-07-21 13:30 UTC, eunii commented on src/main/java/controller/LottoController.java
> +        List<Lotto> lottoTickets = lottoMachine.getLottoTickets();
넵 Lottos객체로 클래스를 한번 더 감쌌습니다.

2021-07-21 13:31 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +     public List<Integer> getWinningNumber(String winningNumber) {
기본 인풋 검증값은 InputValication, 로또 로직이 들어간 검증값은 LottoValication 으로 분리하였습니다. 
LottoValication은 Lotto객체나 LottoMachine에서 처음 값을 받는 생성자에서 검증하도록 구현하였습니다.

2021-07-21 13:32 UTC, eunii commented on src/main/java/domain/Lotto.java
> +        countOfBonusMatch(bonusNumber);
앗 ㅠㅠ이런실수는 없애야겠네요

2021-07-21 13:34 UTC, eunii commented on src/main/java/domain/LottoMachine.java
> +     public List<Integer> getWinningNumber(String winningNumber) {
아래 InputValidation 코멘트 주신 내용에 답글 다는 창이 활성화 안되서 여기 남깁니다ㅠ.
제가 로또번호를 검증하는 로직을 당첨번호  체크하는 부분만 적용했더라구요. Lotto클래스 생성자에서 체크하도록 추가했습니다.