로또 게임 2단계 리뷰 요청 드립니다!
kiworkshop/java-lotto pull request #17
Opened 2021-07-29 09:42 UTC by seongbeenkim

안녕하세요 시영 선생님
2단계 로또 게임 리뷰 요청드립니다!

### 학습 로그
[AssertJ](https://assertj.github.io/doc/)
- extracing, tuple 등 테스트 코드에서 유용하게 쓸 수 있는 기능

2021-08-03 10:35 UTC, KIMSIYOUNG requested changes
안녕하세요 성빈님 🙂 

수동 로또 기능도 잘 작성해주셨네요! 

몇가지 코멘트 남겼으니 확인후에 말씀 부탁드립니다!

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        BuyerRequest buyerRequest = new BuyerRequest(inputPurchaseAmount);
단순히 변환을 위한 DTO로 보이는데요! 

해당 DTO가 자신이 가지고 있는 데이터를 통해, 도메인인 PurchaseAmount 를 생성하는 형태는 어떨까요? 자주 변경되는(DTO)곳에서 자주 변경되지 않는 도메인으로의 참조니까요!

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        LottoTickets manualTickets = LottoTicketGenerator.createManualTickets(lottoTicketsRequest.getManualLottoNumbers());
동일한 방식이지만, 수동로또에 자동로또를 추가하는 느낌 보단, 새로운 `lottoTickets` 리스트를 선언해서 여기에 두가지 타입을 담는게 가독성이 더 좋을 것 같아요!

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/test/java/lotto/domain/dto/response/WinningStatisticsResponseTest.java
>          assertThat(winningStatisticsResponse.list()).hasSize(5)
가독성이 좋네요👏

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Buyer.java
> +        if (currentAmount.isLessThan(numberOfManualTickets.getPaidPurchaseAmount())) {
개인적으로 중요한 validation 이라고 생각하는데 꼼꼼한 검증 👏

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Buyer.java
> +        int leftAmount = currentAmount.deduct(numberOfManualTickets.getPaidPurchaseAmount());
로또금액을 가지고, 티켓의 갯수를 계산할 수 있는 역할은 LottoTicketCount가 적절해보이는데요. 그렇게 되면 Lotto_TICKET_PRICE도 LottoTicket에 있어야 할 이유도 없지 않을까요? 

추가로 저는 정산팀이라..공제(`deduct`)란 단어가 낯설진 않은데 요 경우에 subtract / minus 정도로도 의미를 충분히 드러낼 수 있지 않을까요?

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoTicketGenerator.java
> +    public static LottoTickets createManualTickets(List<List<LottoNumber>> manualLottoNumbers) {
그리 복잡한 자료구조는 아니지만, 이런 경우에도 일급컬렉션을 통해서 의미를 조금 더 드러낼 수 있을 것 같아요. LottoTicket -> LottoTickets 처럼요! 추가로, 현재 구조에선 발생하지 않지만 자료구조가 위와 같이 복잡해지면 `Null`에 대한 체크도 어려워져요. 이를 일급컬렉션이라는 자료구조로 만들고, 널 체크만 해준다고 해도, 충분히 의미있는 포장이라고 생각이 들어요🙂

```java
        @Test
        void test26() {
            /* when, then */
            assertThatThrownBy(() -> LottoTicketGenerator.createManualTickets(Arrays.asList(null)))
                    .isInstanceOf(NullPointerException.class);
        }
```

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoTicketsCount.java
> +        return new LottoTicketsCount(this.numberOfTickets + lottoTicketsCount.intValue());
같은 클래스내부라서 lottoTicketsCount.numberOfTickects라고도 쓸 수 있습니다🙂 취향따라..

2021-08-03 10:35 UTC, KIMSIYOUNG commented on src/test/java/lotto/domain/LottoTicketsCountTest.java
> +                .isThrownBy(() -> new LottoTicketsCount(0))
요 부분 테스트가 깨지네요🙂
 
테스트가 있기 때문에, 성빈님이 편안하게 수동로또를 리팩토링 할 수 있었다고 생각합니다. 로직이 변경되는 경우 내 프로그램이 예상치 못한 오류가 있진 않을까? 라는 불안감에서 해방될 수도 있구요. 

당연히 실수시겠지만 로직을 변경한다면 제출전엔 꼭 전체 테스트를 한 번 돌려주세요! (테스트의 존재이유 중 하나를 되새기며!)

2021-08-04 13:36 UTC, seongbeenkim commented on src/test/java/lotto/domain/LottoTicketsCountTest.java
> +                .isThrownBy(() -> new LottoTicketsCount(0))
앗.. 리팩토링 후 전체 테스트 케이스 실행하지 않았네요 죄송합니다ㅠㅠ
해당 부분 수정해주었습니다!

2021-08-04 16:48 UTC, seongbeenkim commented on src/main/java/lotto/controller/LottoController.java
> +        BuyerRequest buyerRequest = new BuyerRequest(inputPurchaseAmount);
DTO 내부에서 도메인을 생성해주는 방식으로 하니 외부에서 불필요하게 new로 생성하는 코드를 보여주지 않게 되고 따라서 코드도 더 가독성이 좋아지는 것 같네요!
다른 DTO들도 내부에서 도메인을 생성해주는 방식으로 변경하였습니다!

2021-08-04 17:03 UTC, seongbeenkim commented on src/main/java/lotto/controller/LottoController.java
> +        LottoTickets manualTickets = LottoTicketGenerator.createManualTickets(lottoTicketsRequest.getManualLottoNumbers());
수동 로또에 추가하는 방식이 아닌 수동 로또, 자동 로또를 분리를 해주는 게 더 가독성이 좋다고 생각이 드네요!
말씀하신 것처럼 수정해주었습니다! 감사합니다 :)

2021-08-04 17:17 UTC, seongbeenkim commented on src/main/java/lotto/domain/Buyer.java
> +        int leftAmount = currentAmount.deduct(numberOfManualTickets.getPaidPurchaseAmount());
그러네요 `LottoTicket` 객체 본인이 자신의 가격을 가지고 있는 것도 어색하네요!
가격 `LottoTicketCount`로 옮겨주었으며, 말씀해주신 `deduct`도 더 이해하기 쉬운 `subtract`로 수정하였습니다!

2021-08-04 17:44 UTC, seongbeenkim commented on src/main/java/lotto/domain/LottoTicketGenerator.java
> +    public static LottoTickets createManualTickets(List<List<LottoNumber>> manualLottoNumbers) {
해당 부분 `LottoNumbers`라는 이름으로 일급 컬렉션을 지어줄 경우,
`LottoNumbers`와 `LottoTicket` 둘 다 `List<LottoNumber>`를 관리하는 일급컬렉션이기 때문에
객체 이름만으로는 혼동을 줄 수 있다고 생각하여 `ManualLottoNumbers`로 만들어주었습니다! 

그리고 해당 Collection에서만 null 검사를 할 경우, 현재까지 만들었던 모든 도메인, 일급컬렉션에서 null 검증을 해주지 않고 유효성 검증으로만 구현했던 방식과 일관되지 않다고 생각하여 null 검증을 6개의 수동 번호 개수 검증으로 대채하였습니다!

2021-08-05 02:17 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Buyer.java
> +        int leftAmount = currentAmount.deduct(numberOfManualTickets.getPaidPurchaseAmount());
제가 의도했던건 로또티켓카운트가 금액을 인자로 받았을 때 티켓의 갯수를 반환해주는 것이 어떨까 라는 의견이였습니다!

성빈님이 기존에 작성해주신대로 구매자가 이를 계산하는 역할이 맞다고 생각되면 `LOTTO_TICKET_PRICE` 이 구매자가 가지는 원래 형태가 더 맞는 것 같습니다. (`getPaidPurchaseAmount` 메소드 또한 이 값을 파라미터로 받아야한다고 생각하구요)

금액을 통해 구매할 수 있는 장수를 계산하는 역할이 구매자가 아닌 로또티켓카운트의 역할이라고 리뷰드린거긴합니닷! 요 부분 생각해보시고 의견 부탁드려용

2021-08-05 02:28 UTC, KIMSIYOUNG approved these changes
성빈선생님 안녕하세요🙂

리뷰 반영해주신 부분 잘 보았습니다. 

마지막에 패키지를 분리해주셔서, 패키지에 대해서 조금 고민해보면 좋을 것 같아요. 단순히 디렉토리로써의 기능으로 분리하신 건 아니라고 생각이 되는데(레이어별로 패키지가 있어서요)

이 때 Enum을 별도의 패키지로 둔 이유와 DTO를 도메인패키지내에 둔 이유에 대해서 말씀주시면 좋을 것 같습니다! 별 다른 이유가 없다면 어떤 패키지에 해당 클래스들이 들어가면 좋을지도 고민해보면 좋을 것 같아요!

2021-08-05 02:28 UTC, merged

2021-08-05 10:15 UTC, seongbeenkim commented on src/main/java/lotto/domain/Buyer.java
> +        int leftAmount = currentAmount.deduct(numberOfManualTickets.getPaidPurchaseAmount());
시영 선생님 피드백 확인 후, 생각해보니 티켓의 장수 관련한 로직들은
`LottoTicketCount`에서 해주는게 객체 이름에 걸맞는 행위를 하는 것이고 역할이라고 생각이 드네요!
이러한 이유에 있어 금액을 통해 티켓의 장수 계산하는 역할도 `LottoTicketCount`에게 주는 것이 더 좋다고 생각합니다! 

피드백을 통해서 앞으로 가지고 있지 않아야 될 책임, 역할을 가지고 있지 않은 지 한번 더 생각해봐야겠다는 생각이 드네요!
감사합니다 :)

2021-08-05 10:59 UTC, seongbeenkim commented
enum 클래스인 `LottoRank`는 domain에 속하는 개념이라고 생각했지만 enum 클래스라는 것을 명시해주기 위해서 일단 `enums` 패키지로 분리 해줬었습니다. 

하지만 모든 기능 구현 후 패키지 정리를 하면서
1. `enums` 패키지를 `domain` 패키지 하위에 넣기
2. `enums` 패키지를 제거하고 `LottoRank`만 `domain` 패키지에 넣기
3. 그대로 유지 - `enum`, `domain` 패키지 동일 레벨에 두기
이렇게 3가지 구조를 생각해봤지만, 현재 프로그램에서는 그대로 유지를 해줘도 괜찮지 않을까해서 그대로 유지하였습니다!

앗.. dto는 controller 패키지 하위로 옮겨준다고 하고 옮겨주지 않았네요.. 
DTO는 계층간에 데이터를 전달해주는 객체라고 생각했기 때문에 `view`와 `domain`을 이어주는 `controller` 하위에 넣어두었습니다!

이렇게 적용하였던 두 부분에 조언을 해주실 수 있으실까요?
그리고 패키지 분리하는데 있어서 많이 미숙한데 혹시 공부할만한 키워드나 서적 추천을 해주실 수 있으실까요?!!

2021-08-05 11:22 UTC, KIMSIYOUNG commented
패키지를 단순히 디렉토리의 개념으로 본다면 enums도 하나의 집합으로써 패키지를 만드는 것도 괜찮아보입니다. 다만 패키지가 레이어를 의미한다면 각 레이어의 성향을 드러낼 수 있는 것이 좋다고 생각합니다. 도메인레이어(패키지)에 있는 파일들은 결국 어떠한 `문제`를 해결하기 위한 단위로써 존재하고, 그 문제의 단위가 패키지의 단위가 되는 것이 좋다고 생각해요. 그런 의미에서 현재 구조에서는 2번이 적절해보입니다. 
물론 도메인을 더 세분화된다면 도메인 패키지내에서도 다시 `문제`의 단위로 패키지가 분리되는 것이 좋을 것 같아요. 현재는 로또라는 작은 프로그램이지만, 이커머스로 가정한다면 도메인은 주문/결제/정산 등의 다양한 것들로 나눠질 수 있을 것 같아요. (물론 도메인별로 패키지를 분리해서 내부적으로 다시 레이어를 가져가는 구조도 있지만, 요 부분은 해당 미션과는 조금 벗어나는 것 같아서 제외할게요)
즉 제 생각은, 레이어단위로 패키지를 분리한 시점에서 enums를 패키지로 만드는 것은 레이어의 개념과 디렉토리의 개념이 혼재한다고 생각이 들어요. 

앗 DTO에 대한 생각은 저도 동일합니다🙂 현재는 단순한 구조이기에 View와 Domain만을 연결하는 DTO이지만 레이어가 다양해진다면 각 레이어간의 이동을 위해서도 추가적인 DTO가 필요할 수 있겠죠? 예를 들어 서비스레이어가 추가되고, 컨트롤러는 사용자 입력값에 맞게 DTO를 만들고 해당 DTO를 서비스에서 원하는 포맷의 DTO로 변환하는 작업이 추가될 수도 있을 것 같아요. 

일반적으로 레이어 아키텍처가 사용되기 때문에 레이어 아키텍쳐에서 각 레이어의 역할이 무엇이고, 그 레이어들간의 관계는 어떻게 설정되는 것이 바람직한지, 관계에 양방향은 없는지 등을 고려하면서 개발하면 좋을 것 같습니다. 아래의 키워드로 각 아키텍처가 어떤 형태를 띄고, 그 안에서 어떤 객체들이 존재하고 그 객체의 역할과 의존의 방향성등을 보면서 학습하면 좋을 것 같습니다. 
- 레이어드 아키텍처 
- 헥사고날 아키텍처 

여담으로 패키지는 사실 우리가 이름으로 의미를 부여하는 것이지, 사실 디렉토리에 불과합니다. 이에 패키지간의 의존성을 알기 힘듭니다. (import를 열심히 보지 않는 이상) 예를 들어 도메인 레이어에서 `presentation` 레이어를 참조하면 안된다라는 사실을 알고 있어도, 아무렇지 않게 프레젠테이션 패키지의 DTO를 도메인 패키지를 사용할 수도 있습니다. 다만 이를 강제하기 위해서 각 패키지를 `모듈`로 분리하면 모듈간의 의존성을 직접 넣어주지 않으면 참조할 수 없기 때문에 극단적으로 각 레이어를 분리할 수 있는 좋은 방법이 될 것 같아요. (모듈이라는 개념은 레이어와는 다르지만, 모듈에 레이어 개념을 적용해서 사용한다 정도로 인지하고 사용하시면 어렵지만, 의존성을 잘 알 수 있어서 좋아요)
- 멀티모듈 < 이라는 키워드로 검색하셔서 구성하셔도 되고, 어려우시면 말씀해주세요! 
- 사실 모듈로 나눠서 연습하는 건 극단적인 케이스라 굳이..하지 않으셔도 됩니다. (안하는걸 추천하기도 합니닼ㅋㅋ)