[로또 게임 2단계] 리뷰 요청 드립니다.
kiworkshop/java-lotto pull request #18
Opened 2021-08-08 10:34 UTC by chunghyeon-kim

1단계 마지막부분에서 코멘트 주신대로 enum을 하나로 통합했습니다.

prizeMessage를 toString 오버라이딩으로 처리했는데 혹시 더 좋은 방법이 있는지 궁금합니다.

2021-08-15 02:38 UTC, me0768 requested changes
충현선생님 고생많으셨습니다. 1단계에 비해 코드에 중복이 없고 객체도 책임에 따라 잘 분리된 코드가 되었네요.

몇가지 코멘트 남겼는데 확인해주세요 :)

2021-08-15 02:38 UTC, myangw commented on src/main/java/lotto/constant/Prize.java
> +        if (this.equals(FIFTH)) {
toString으로 바꾸신것 많은 고민끝에 나온 개선점이라 생각듭니다 👏 

이대로도 나쁘지않지만 메시지 출력용 메서드로 만들어놓으면 좀더 명시적일 것 같아요.

그리고 FIFTH -> SECOND를 의도하신거같은데 잘못 적으신듯합니당

2021-08-15 02:38 UTC, myangw commented on src/main/java/lotto/domain/PrizeCount.java
> +        if(condition.equals(Prize.FIRST)) {
여기 메서드에 있는 5개의 비슷한 if문을 줄일 수 있는 좋은 방법이 없을까요.

Prizecount 클래스에 저렇게 필드를 각각 저장하기보다 어떤 자료구조 안에 포함시키면 코드를 확 줄일 수 있을것 같아요.

이미 고민해보셨는데 어려우셨거나 이렇게 하신 이유가 있으시다면 코멘트 달아주세요.

2021-08-15 02:38 UTC, myangw commented on src/main/java/lotto/domain/WinningLotto.java
> +        return Prize.findPrize(getMatchNumbersCount(targetLotto), isBonusMatch(targetLotto));
지난 리뷰때 제가 놓친 부분이 있는데 이번에 변경이 없어서 여기에 코멘트남깁니다.

`getMatchNumbersCount()` 메서드 구현에 while문 안에 if else가 있어서 indent depth가 2단계까지 들어가고 있잖아요, 이부분 알고리즘 상 어쩔 수 없는건가 하고 넘겼었는데  지금 보니까 Set을 활용하면 해결가능할 것 같습니다.

Set이라는 자료구조는 중복을 허용하지 않아서, 같은 객체를 삽입하면 마지막에 삽입된 것 하나만 저장하게 됩니다. 이 속성을 이용하면 두개의 로또번호들 중 몇개가 중복되지 않는지 구할 수 있을거에요.

2021-08-15 02:38 UTC, myangw commented on src/main/java/lotto/domain/PurchaseCount.java
> +        this("" + (Integer.parseInt(purchasePriceInputDTO.getInput()) - Integer.parseInt(manualPurchaseCountDTO.getInput()) * Lotto.PRICE));
여기서 굳이 위의 String input을 받는 생성자를 다시 쓰기보다 별개의 로직으로 validate하고 필드에 넣어주는 로직을 쓰면 좋겠습니다. 

input에 Price를 곱했다가 다시 나누는 계산을 하게되는데, 다른 생성자를 재사용해서 더 계산이 줄어들기보다 늘어났다는 생각이 들어서요.

2021-08-15 02:38 UTC, myangw commented on src/main/java/lotto/domain/PurchaseCount.java
> +        this("" + (Integer.parseInt(purchasePriceInputDTO.getInput()) - Integer.parseInt(manualPurchaseCountDTO.getInput()) * Lotto.PRICE));
![image](https://user-images.githubusercontent.com/26712339/129464537-19c31507-ecf6-444f-837e-334ce4f05d8d.png)

수동으로 모두 살 수도 있어야할 것 같은데 exception 발생되네요

2021-08-15 02:38 UTC, me0768 commented on src/main/java/lotto/controller/LottoController.java
>          View view = new View();
View 객체가 Controller에 종속되는 구조인데(다른 View객체를 쓰고싶어 수정을 하게되면 컨트롤러도 같이 수정되어야하는..!)  이걸 독립적으로 바꿔줘야 MVC 패턴을 적용했다고 볼 수 있을 것 같아요.

그리고 MVC패턴에서 컨트롤러도 여러개가 존재할 수 있고 M,V,C 각각 변동될 수 있음을 생각하면 static보다 하나의 객체로 생성되면 좋겠어요.

정리하면 컨트롤러 외부(main메서드) 에서 View객체를 생성하고, 컨트롤러에 파라미터로 넣어주는 식으로 변경해볼 수 있습니다. 이걸 "의존성주입"이라고 하는데요. 나중에 Spring framework 쓸때 많이 사용되는 개념입니다. 아직 스프링을 사용해보시지 않았다면 이해가 어려우실 수도 있겠지만 [우빈쌤이 DI에 대해 설명한 글](https://wbluke.tistory.com/9) 도 한번 읽어보시면 조금은 도움될 것 같아요. 


MVC패턴에 대해  한방에 다 이해되는 좋은 자료는 못찾았는데ㅜㅜ 우선 아래 링크들도 읽어보시면 좋겠습니다.
https://medium.com/@jang.wangsu/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-mvc-%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80-1d74fac6e256


https://ko.wikipedia.org/wiki/%EB%AA%A8%EB%8D%B8-%EB%B7%B0-%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC

2021-08-22 06:43 UTC, chunghyeon-kim commented on src/main/java/lotto/constant/Prize.java
> +        if (this.equals(FIFTH)) {
메세지 출력용 메서드 prizeMessage를 만들었습니다.
등수와 일치하는 번호 개수를 헷갈린 것 같습니다. 수정했습니다 ^^;

2021-08-22 06:49 UTC, chunghyeon-kim commented on src/main/java/lotto/domain/PrizeCount.java
> +        if(condition.equals(Prize.FIRST)) {
여러개의 int 필드들 대신 int 배열을 선언해서 등수를 카운트하도록 변경했습니다.
말씀해주신대로 반복되는 코드를 확 줄일 수 있었습니다!

2021-08-22 06:50 UTC, chunghyeon-kim commented on src/main/java/lotto/domain/WinningLotto.java
> +        return Prize.findPrize(getMatchNumbersCount(targetLotto), isBonusMatch(targetLotto));
와! Set을 사용하니 코드가 정말 간단해졌습니다.
중복체크는 Set으로!! 앞으로도 계속 기억하겠습니다. ㅎㅎ

2021-08-22 06:54 UTC, chunghyeon-kim commented on src/main/java/lotto/domain/PurchaseCount.java
> +        this("" + (Integer.parseInt(purchasePriceInputDTO.getInput()) - Integer.parseInt(manualPurchaseCountDTO.getInput()) * Lotto.PRICE));
String 생성자를 사용하지 않는 방식으로 변경했습니다.
최소 구입금액에 대한 유효성검사를 PurchasePriceInputDTO의 생성자가 수행하도록 변경했습니다.
이제 전체 구입금액을 수동으로 구매할 수 있습니다.

2021-08-22 06:56 UTC, chunghyeon-kim commented on src/main/java/lotto/controller/LottoController.java
>          View view = new View();
기존의 View 클래스를 LottoView로 이름을 바꾸고 View 인터페이스를 선언해서 LottoView가 View 인터페이스를 구현하도록 했습니다.
그리고 Controller의 생성자가 View 타입의 매개변수를 받도록 해 View를 갈아끼울 수 있도록 수정했습니다.

좋은 레퍼런스 찾아주셔서 감사합니다! 꼼꼼하게 몇번 더 읽어보겠습니다.

2021-08-28 06:12 UTC, me0768 commented
반영된 부분 확인했습니다. 고생 많으셨습니다. 머지할게요 :)

2021-08-28 06:12 UTC, merged