Step1 - 로또 게임
kiworkshop/java-lotto pull request #9
Opened 2021-07-07 16:26 UTC by pageprologue

### 학습로그

- [equals() & hascode()](https://velog.io/@sonypark/Java-equals-hascode-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C)
  - 두 값 객체를 equals로 비교한다는 것은 객체가 같은지가 아니라 값이 같은지 알고 싶은 것이다.
  - 양질의 equals 메서드 구현 방법
      - == 연산자를 사용해 입력이 자기 자신의 참조인지 확인한다.
      - instanceof 연산자로 입력이 올바른 타입인지 확인한다.
      - 입력을 올바른 타입으로 형변환한다.(2번에서 instanceof 검사를 했으니 100% 성공한다.)
      - 입력 객체와 자기 자신의 대응되는 '핵심' 필드들이 모두 일치하는지 하나씩 검사한다.
      - equals를 재정의할 땐 hashCode도 반드시 재정의한다.

- [자바 Enum 기본 및 활용](https://velog.io/@kyle/%EC%9E%90%EB%B0%94-Enum-%EA%B8%B0%EB%B3%B8-%EB%B0%8F-%ED%99%9C%EC%9A%A9)
    - 클래스를 상수처럼 사용 할 수 있다.
    - Enum 클래스를 구현하는 경우 상수 값과 같이 유일하게 하나의 인스턴스가 생성되어 사용된다. 
    - 서로 관련 있는 상수 값들을 모아 enum으로 구현하는 경우 유용하다.
    - 클래스와 같은 문법 체계를 따른다.
    - 상속을 지원하지 않는다.

2021-07-11 16:08 UTC, jjj0611 requested changes
희진 선생님 로또 미션 1단계 구현하시느라 고생 많으셨습니다! 👍 

로또라는 도메인이 매우 친숙한 것 같아보여도 생각보다 고민해야할 것들이 많아서 쉽지 않았을텐데 잘 구현해주셨네요.

고민이 될만한 지점들 코멘트 조금 남겼으니 확인 부탁드려용 :)

2021-07-11 16:08 UTC, jjj0611 commented on README.md
> +  - [x] 당첨 순위의 수익률을 계산한다.
기능 목록을 매우 잘 작성해주셨습니다 :)
작은 단위로 구분하여 기능 목록을 작성해주신 것이 너무 좋아요.
어떤 상황에서 ERROR가 나는지도 잘 적어주셨네요.

약간 제 개인적인 의견을 살짝 붙이자면, ERROR를 기준으로 정의를 하기보다는 정상 상황에 대한 정의를 하는 것이 조금 더 좋지 않나?라는 생각이 들긴 합니다!

예를 들어서,
로또 넘버
- ERROR: 1~45의 숫자가 아닐 경우 예외가 발생한다.

보다는

로또 넘버
- 로또의 숫자는 1~45까지의 숫자만 가능하다.
	- 그 외의 숫자로 로또 번호가 생성될 시 예외가 발생한다.

와 같이 정상 case에 대한 언급과 그 외의 케이스에 대한 것으로 명시하면 조금 더 이 기능에 대해 잘 이해할 수 있지 않을까 하는 조심스러운 개인적인 의견이 있습니다!

희진 선생님께서도 고민 한 번 해보시면 좋을 것 같아요 :)


또한 여기서 로또 넘버, 로또 티켓, 로또 티켓 머신과 같은 내용이 반영되어 있는 점이 매우 좋습니다. 실제로 사용되는 이러한 용어들(누군가는 도메인 용어라고 부르는)을 잘 사용하는 것이 매우 중요합니다. 아마 로또에 대해 생각해보지 않은 사람들은 로또 티켓이 무엇인지 모를 확률이 매우 높아요. 그런데 조금만 로또에 대해 공부를 해보면 우리가 어떤 이름으로 그것들을 부르는지 이것을 어떻게 코드에 적용할지에 대한 고민이 좋은 코드를 만드는 초석이라고 생각합니다 :) 👍🏻

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/LottoApplication.java
> +        lottoController.run();
MVC 패턴을 적용하려고 노력한 부분이 보이네요
그런데 lottoController가 인스턴스로 생성되어야 하는 이유가 어떤 걸까요?
Run이라는 메서드를 static하게 만들어서 LottoController.run();으로 호출하는 것과는 어떤 차이가 있을까요?

정답이 있는 질문은 아니고, 어떤 의도를 가지고 이렇게 생성해서 만들었는지, static하게 만들어서 작동하면 뭐가 다른지 고민 해보시면 좋을 것 같아요 :)

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/controller/LottoController.java
> +        List<LottoTicket> lottoTickets = lottoTicketVendingMachine.issueTickets(buyingPrice);
벤딩머신이 게임이 run 될 때마다 한 번씩 생성이 될 것 같아요.
그런데 벤딩머신은 금액을 입력 받아서 로또를 출력해주는 기능을 가지고 있는데 매번 생성할 필요가 있을까요?

Run을 한 번 하는 단위가 고객 한 명이 로또 판매점에서 로또를 구입하는 과정이라 생각하면 손님 한 명마다 로또를 뽑아주는 기계를 1개씩 새로 들여오는 셈이죠!

무분별한 재활용은 코드 퀄리티를 낮출 수 있지만,
적절한 재활용은 자원을 아낄 수 있는 중요한 방법입니다 :)

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/BuyingPrice.java
> +    }
조금 더 친절한 메서드명을 써주면 어떨까요?
인자를 검증한다 == 구입 금액이 1000원 단위인지를 확인한다
`구입 금액이 1000원 단위어야 한다`는 이 로또 게임의 정책이라고 생각해요.
일정 단위로 떨어지는지를 검증한다는 내용을 조금 더 친절하게 적어주면 코드를 읽는데 더 도움이 될 것 같아요 :)

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/BuyingPrice.java
> +            throw new IllegalArgumentException("구입 금액은 1,000원 단위여야 합니다.");
만약 로또 금액이 2000원 단위로 구입이 가능하게 바뀐다면
TICKET_PRICE의 값을 2000으로 변경을 하게 될텐데
실수로 메시지를 변경하지 못 했다면 어떻게 될까요?

휴먼 에러를 조금 더 줄이는 방법은 어떤 것들이 있을까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/BuyingPrice.java
> +    }
지금 현재 buyingPrice는 벤딩 머신 안에 있는 1000원에 매우 의존적인 상황이에요.

1000원이 `구입 금액`에 조금 더 가까운 정책인지 벤딩 머신에 조금 더 가까운 정책인지 고민해보면 좋을 것 같습니다!

특히 이 divide라는 메서드를 보고 조금 고민이 들었는데, 이 메서드는 고객에게 몇 장을 구입했는지 출력할 때 장수를 알려주기 위해 존재하는 메서드로 보여요.
그런데 만약 divide의 인자를 밖에서 잘 못하여 10으로 입력을 하는 경우 어떤 문제가 일어날까요?

만약 이 객체가 구입 금액이 아니고 단순한 Price였다면 로또 티켓 금액을 가지고 나누는 것이 좋겠지만, 구입 금액이라는 도메인이 되었을 때는 조금 다른 상태가 되어야 한다고 생각이 듭니다!
혹은 티켓 구매 가격을 기반으로 몇 장을 구입 가능한지에 대한 메서드를 다른 방향으로 풀면 어땠을까? 하는 고민도 드네요!

한 번 고민해봐주세요 :)

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/LottoGenerator.java
> +    private static final List<LottoNumber> lottoNumberContainer = create();
static 변수의 네이밍 컨벤션을 찾아보고 적용해보면 어떨까요?

물론 컨벤션은 같이 일하는 사람하고 정하는 것이 맞다고 생각하지만, 그럼에도 각 언어에서 통상적으로 사용하는 컨벤션이 보통 존재하고, 그것에 맞춰서 코드를 작성하는 것이 좋지 않을까 생각합니다 :)

로또 번호를 미리 생성해두고 재활용하는 것이 매우 좋은 재활용 방법이라고 생각합니다 👍

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/LottoTicket.java
> +    }
```
new LottoTicket(Arrays.asList(1,2,3,4,5,6,7,8,9,10...45));
```

를 하면 어떤 일이 벌어질까요...?

혹은

```
new LottoTicket(Arrays.asList(1,1,1,1,1,1));
```

를 호출하면 어떤 일이 벌어질까요?


로또 티켓에 대한 기능 목록과 실제 로또 티켓이 기능하는 것이 다른 것 같아요!

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/WinningStatistics.java
> +        }
indent를 1단계로 줄여보는건 어떨까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/view/OutputView.java
> +                    lottoPrize.prizeMoney(), ranks.get(lottoPrize));
역시 indent를 1로 줄여보는건 어떨까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/view/OutputView.java
> +public class OutputView {
InputView는 static 메서드를 사용하기 위해 생성자를 일부러 막아두신 것 같은데,
해당 클래스는 생성이 가능한 상태입니다.

혹시 둘 사이의 차이를 두신 이유가 있을까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final Map<LottoPrize, Integer> ranks = new LinkedHashMap<>();
WinningStatistics가 내부적으로 Map<LottoPrize,Integer>를 들고 있으면,
groupByWinningNumber();를 호출 할 떄마다 데이터가 계속 쌓일 것 같은데,
그렇게 되면 어떤 문제가 발생할 수 있을까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/WinningStatistics.java
> +                .forEach(v -> ranks.put(v, 0));
이번 프로그래밍 요구 사항 중에 축약하지 말라!가 있었던 것 같은데,
지금 너무 많은 것들이 축약되어 있는 것 같아요.
일단 values()로 호출을 하면 어떤 Enum을 사용할 것인지 한 번 더 고민을 해봐야하고,
그 뒤에 filter에서 v로 표현한(아마 value를 의미하셨을 것 같은데) 것이 무엇을 의미하는지도 알기 힘든 것 같아요.

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/LottoPrize.java
> +    NONE(0, false, 0);
당첨되지 않은 상태를 NONE으로 부르는 것이 조금 어색한 것 같아요.
조금 더 의미 부여를 해보면 어떨까요?

2021-07-11 16:08 UTC, jjj0611 commented on src/main/java/lotto/domain/LottoPrize.java
> +    }
테스트에서밖에 사용이 안되는 메서드인 것 같은데,
어떤 의도로 만든 메서드인가요?

2021-07-11 16:08 UTC, jjj0611 commented on src/test/java/lotto/BuyingPriceTest.java
> +    }
BuyingPrice의 생성자를 테스트한 걸까요? equals를 테스트한 걸까요?
전자라면 해당 테스트에 어떤 의미가 있는지를 고민해보면 좋을 것 같고,
후자라면 테스트 제목과 설명이 변경이 되어야 할 것 같아요!

2021-07-11 16:08 UTC, jjj0611 commented on src/test/java/lotto/BuyingPriceTest.java
> +                .withMessage("구입 금액은 1,000원 이상이여야 합니다.");
👍 

```
        assertThatThrownBy(() -> new BuyingPrice(invalidPrice))
            .isInstanceOf(IllegalArgumentException.class);
```

이런 방식으로도 테스트 할 수 있습니다!

2021-07-11 16:08 UTC, jjj0611 commented on src/test/java/lotto/WinningNumbersTest.java
> +    }
ParameterizedTest와 methodSource를 활용해보는 것 매우 좋습니다 👍 
다만 위와 같은 경우 첫번째 인자를 List형이 아닌 배열로 받은 이유가 있을까요?

2021-07-15 10:19 UTC, pageprologue commented on src/main/java/lotto/LottoApplication.java
> +        lottoController.run();
static 메서드는 인스턴스 변수나 인스턴스 메소드를 사용할 수 없습니다. 그래서 모든 인스턴스에서 공통적인 값을 가져야 하는 경우 static 으로 선언하는 것이 좋습니다.

2021-07-15 10:21 UTC, pageprologue commented on src/main/java/lotto/controller/LottoController.java
> +        List<LottoTicket> lottoTickets = lottoTicketVendingMachine.issueTickets(buyingPrice);
말씀해주신 대로 재활용 할 수 있도록 이 부분도 클래스 변수로 빼 두었습니다.

2021-07-15 10:24 UTC, pageprologue commented on src/main/java/lotto/domain/BuyingPrice.java
> +    }
factor 가 수학 용어로 "인수" 라고 하길래 나누어 떨어질 수 있는 값으로 표현해 보았는데, 의미가 명확하지 않을 것 같아서 메소드 명을 validateDivisible 로 수정했습니다.

2021-07-15 10:26 UTC, pageprologue commented on src/main/java/lotto/domain/BuyingPrice.java
> +            throw new IllegalArgumentException("구입 금액은 1,000원 단위여야 합니다.");
메시지 부분도 상수 값(TICKET_PRICE) 으로 대체했습니다 :)

2021-07-15 10:29 UTC, pageprologue commented on src/main/java/lotto/domain/BuyingPrice.java
> +    }
BuyingPrice 객체에서 divide 메소드를 통해 티켓 장 수를 가져오려고 했던 부분인데, 티켓 장 수를 TicketAmount 라는 객체로 생성하도록 수정했습니다.

2021-07-15 10:56 UTC, pageprologue commented on src/main/java/lotto/domain/LottoTicket.java
> +    }
이 부분은 생성자의 파라미터가 List<LottoNumber> 로 넘어오기 때문에 중복된 숫자는 LottoNumber 에서 예외 처리가 되어 있습니다.
로또 티켓이 6개 보다 많은 경우 예외 처리가 되지 않고 있어서, 이 경우에 대한 예외 처리 기능을 추가하였습니다.

2021-07-15 11:00 UTC, pageprologue commented on src/main/java/lotto/view/OutputView.java
> +public class OutputView {
정적 클래스는 인스턴스 생성을 방지하기 위해 방어 로직으로 private 생성자를 두는 것이 좋다고 피드백 받은 내용을 한 곳에만 적용했네요..ㅎㅎ

2021-07-15 11:03 UTC, pageprologue commented on src/main/java/lotto/domain/LottoPrize.java
> +    }
로또 상금을 출력해 주는 부분에서 사용하려고 했는데요. 다른 방식으로 수정하면서 이 메소드는 삭제하였습니다.

2021-07-15 11:11 UTC, pageprologue commented on src/main/java/lotto/domain/WinningStatistics.java
> +    private final Map<LottoPrize, Integer> ranks = new LinkedHashMap<>();
테스트 해보니, 데이터가 쌓이는 문제가 있었습니다. 이 부분은 WinningLottoRank 객체를 추가하여, 객체를 생성할 때 데이터를 세팅하도록 수정하였습니다.

2021-07-15 11:18 UTC, pageprologue commented on src/test/java/lotto/BuyingPriceTest.java
> +    }
후자였는데요. 구입 금액은 값이 같으면 해당 인스턴스를 같다고 봐도 될 것 같아서 값 객체로 생성하여 비교하는 테스트를 의도하였습니다.

2021-07-15 11:20 UTC, pageprologue commented on src/test/java/lotto/WinningNumbersTest.java
> +    }
원래는 List<LottoNumber>를 인자로 받아 LottoTicket 객체를 생성하는데요. 
테스트 코드 작성시에 번거로워서 LottoTicket(int... lottoNumbers) 으로 된 생성자를 열어두었습니다.

2021-07-17 04:10 UTC, jjj0611 approved these changes

2021-07-17 04:10 UTC, merged